In [1]:
from sklearn.datasets import make_multilabel_classification
from torch.utils.data import Dataset
import torch

In [2]:
def make_dataset():
    x, y = make_multilabel_classification(
        n_samples=10000, n_features=12, n_classes=5, n_labels=2, random_state=1
    )
    # use 9900 samples for training
    x_train = x[:9900]
    y_train = y[:9900]
    # use 100 samples for testing
    x_test = x[-100:]
    y_test = y[-100:]
    return x_train, y_train, x_test, y_test

In [5]:
dataset = make_dataset()

In [23]:
dataset

(array([[ 5.,  4.,  1., ...,  1.,  9.,  2.],
        [ 4.,  5.,  3., ...,  4.,  1.,  3.],
        [ 4.,  0.,  3., ...,  5., 12.,  0.],
        ...,
        [ 1.,  7.,  6., ...,  7.,  2.,  1.],
        [ 5.,  6.,  3., ...,  5.,  1.,  0.],
        [ 3.,  5.,  3., ...,  5.,  8.,  2.]]),
 array([[1, 1, 0, 1, 1],
        [0, 1, 0, 0, 1],
        [0, 1, 0, 0, 1],
        ...,
        [0, 1, 0, 0, 0],
        [1, 1, 0, 1, 0],
        [0, 0, 0, 0, 0]]),
 array([[3., 3., 7., ..., 1., 0., 1.],
        [1., 3., 4., ..., 6., 1., 3.],
        [1., 5., 5., ..., 4., 5., 4.],
        ...,
        [2., 6., 2., ..., 2., 5., 2.],
        [2., 6., 7., ..., 0., 1., 2.],
        [5., 0., 1., ..., 3., 7., 1.]]),
 array([[1, 1, 0, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 1, 0, 1, 1],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [1, 1, 1, 1, 1],
        [0, 1, 0, 0, 0],
        [1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 1, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
 